version: "3"

services:
  mongo:
    image: mongo:3.6
    networks:
      - unifi
    restart: always
    volumes:
      - db:/data/db
  controller:
    image: hannahsfamily/unifi-controller:${TAG:-5.10.25}
    depends_on:
      - mongo
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    networks:
      - unifi
    ports:
      - 3478:3478/udp # STUN
      - 6789:6789/tcp # Speed test
      - 8080:8080/tcp # Device <-> controller communications
      - 8443:8443/tcp # Controller GUI/API
      - 8880:8880/tcp # HTTP portal redirection
      - 8843:8843/tcp # HTTPS portal redirection
      - 10001:10001/udp # AP discovery
    restart: always
    volumes:
      - data:/var/lib/unifi
      - log:/var/log/unifi

volumes:
  db: {}
  data: {}
  log: {}

networks:
  unifi: {}
